# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
pool:
  vmImage: 'ubuntu-latest'

trigger:
  branches:
    include:
      - main

steps:
# ASP.NET Core
- task: UseDotNet@2
  displayName: "Install .NET Core 3.1.x"
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- script: dotnet publish './src/Server/Steeltoe.Server.csproj' --output './publish' --configuration Release --framework netcoreapp3.1 --runtime linux-x64 --self-contained
  displayName: 'dotnet publish project'

- task: CopyFiles@2
  displayName: "Copy publish result to staging"
  inputs:
    SourceFolder: './publish'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/publish'
    CleanTargetFolder: true

- powershell: cp "Dockerfile" "$(Build.ArtifactStagingDirectory)/Dockerfile"
  displayName: "Copy Dockerfile"
  
- powershell: cp "deployment-master.yaml" "$(Build.ArtifactStagingDirectory)/deployment.yaml"
  displayName: "Copy kubernetes manifest"
  
- task: PublishBuildArtifacts@1
  displayName: "Upload Artifacts"
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
